import "./globals.css";
import localFont from "next/font/local";
import type { Metadata } from "next";
import Header from "../components/header";
import Background from "../components/background";

const hubot = localFont({
  src: "../../public/HubotSans.woff2",
  variable: "--font-hubot",
  weight: "400 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={hubot.className}>
      <body>
        <Background>
          <Header />
          {children}
        </Background>
      </body>
    </html>
  );
}
